title: 코딩고구마의 성공기 (●'◡'●)
description: Hello! I'm steaDeveloper Cutiepazzipozzi!
avatar: /logo2.png
email: sk000801@naver.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Seokyung Lim
  links:
    - https://velog.io/@ddungdding
    - https://blog.naver.com/sugamypapa
    - https://github.com/Cutiepazzipozzi
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
